version: "3.9"
services:
  dashboard:
    image: dashboard:latest
    ports:
      - "8080:80"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    env_file:
      - .env

  sensor:
    image: sensor:latest
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    env_file:
      - .env

networks:
  webnet:
